# Generated by Django 4.2.7 on 2024-01-20 01:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('birth_date', models.DateField()),
                ('client_category', models.CharField(choices=[('GRP', 'Группа'), ('IND', 'Гость')], default='IND', max_length=3)),
                ('photo', models.ImageField(upload_to='client_photos')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INW', 'В работе'), ('AWR', 'Жду брони'), ('RES', 'Забронировал')], default='INW', max_length=3)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('flight_number', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_info', models.TextField(blank=True, null=True)),
                ('transfer_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discounts', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_payment_due', models.DecimalField(decimal_places=2, max_digits=9)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_management.clients')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
